version: 0.0
os: linux
files:
  - source: /
    destination: /pkg/stack/stage/NANOPAY
permissions:
  - object: /pkg/stack/stage/
    pattern: "**"
    owner: root
    mode: 777
    type:
      - file
hooks:
  AfterInstall:
    - location: deploy.sh
      runas: root
