version: 0.0
os: linux
files:
  - source: /
    destination: /pkg/stack/stage/NANOPAY
permissions:
  - object: /pkg/stack/stage/NANOPAY
    owner: root
    mode: 777
#hooks:
#  AfterInstall:
#    - location: gen.sh
#      runas: root