version: 0.2

phases:
  install:
    #These depende on 'standard' Ubuntu image, v5.0
    runtime-versions:
      java: corretto11
      nodejs: 12
    commands:
      - echo phase install...

  pre_build:
    commands:
      - echo phase pre_build...
      - add-apt-repository ppa:cwchien/gradle
      - apt-get update -y
      - apt upgrade -y gradle
      - gradle --version
      - apt-get install -y maven
      # Copy foam repository, at desired branch/commit, into place
      - cp -rv $CODEBUILD_SRC_DIR_nanopay_foam/ $CODEBUILD_SRC_DIR/
      - cd $CODEBUILD_SRC_DIR
      - ./build.sh -i

  build:
    commands:
      - echo phase build...
      - cd $CODEBUILD_SRC_DIR
      - echo $CODEBUILD_SRC_DIR
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo $CODEBUILD_SOURCE_VERSION
      - cd $CODEBUILD_SRC_DIR_nanopay_foam
      - echo $CODEBUILD_SRC_DIR_nanopay_foam
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION_nanopay_foam
      - echo $CODEBUILD_SOURCE_VERSION_nanopay_foam
      - cd $CODEBUILD_SRC_DIR_technology_operations_repository
      - echo $CODEBUILD_SRC_DIR_technology_operations_repository
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION_technology_operations_repository
      - echo $CODEBUILD_SOURCE_VERSION_technology_operations_repository
      - cd $CODEBUILD_SRC_DIR
      - ./build.sh -uckJ$BUILD_JOURNALS

  post_build:
    commands:
      - echo phase post_build...

artifacts:
  files:
    - $CODEBUILD_SRC_DIR/gradle.properties
    - $CODEBUILD_SRC_DIR/deploy/bin/install.sh
    - target/package/nanopay-deploy-*
    - $CODEBUILD_SRC_DIR_technology_operations_repository/appspec.yml
    - $CODEBUILD_SRC_DIR_technology_operations_repository/codedeployBeforeInstall.sh
    - $CODEBUILD_SRC_DIR_technology_operations_repository/codedeployAfterInstall.sh
    - $CODEBUILD_SRC_DIR_technology_operations_repository/codedeploySetHostMapping.sh
    - $CODEBUILD_SRC_DIR_technology_operations_repository/codedeploySetJAVA_OPTS.sh
    - $CODEBUILD_SRC_DIR_technology_operations_repository/shrc.custom
    - $CODEBUILD_SRC_DIR_technology_operations_repository/codedeployApplicationStart.sh
  discard-paths: yes
