version: 2
jobs:
  shellcheck:
    docker:
      - image: nlknguyen/alpine-shellcheck:v0.4.6
    steps:
      - checkout
      - run:
          name: Check Scripts
          command: |
            find . -type f -name '*.sh' | wc -l
            find . -type f -name '*.sh' | xargs shellcheck --external-sources

  build:
    docker:
      - image: circleci/buildpack-deps:bionic
    working_directory: ~/NANOPAY
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get -y install maven npm nodejs openjdk-8-jdk-headless
      - run: mkdir -p ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run: git submodule sync
      - run: git submodule update --init

      # cache node modules
      - restore_cache:
          keys:
            - node-v1-{{ checksum "package.json" }}
            - node-v1-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: node-v1-{{ checksum "package.json" }}

      # cache maven repositories
      - restore_cache:
          keys:
            - maven-v1-{{ checksum "pom.xml" }}
            - maven-v1-
      - run: sudo ./build.sh -t
      - save_cache:
          paths:
            - ~/.m2
          key: maven-v1-{{ checksum "pom.xml" }}

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
